### ISSUE TITLE
mikedonovan1987@gmail.com

### ISSUE THREAD

**Issue by iwllyu** [mikedon/grunt-dharma#2]
EPEERINVALID grunt-dharma@0.0.4 requires a peer of dharma@^0.0.x but none was installed.

for NPM 3+

**Comment by mikedon** [comment]
Is this when building the project or a project that depends on this?

**Comment by iwllyu** [comment]
Project that depends on this

Do I just need to depend on this project directly? That's what npm 2 warns
when installing dharma
